### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by MacCrazyman** [yigitm/books#5]
# Peer to peer code review

Hello @iwillteixeira , your project is looking very good, the code is clean and the HTML tags are very meaningful.

There are some suggestions you can implement to improve your project:
* You can delete the [Main.js](https://github.com/yigitm/books/blob/227e347be243cebe6bc0fe1b3cf451de41704f08/js/main.js) as it is part of your previous milestone.
* You can include a screenshot of your project in the Readme file to improve your documentation.
* It would be very good to deploy your application and include a link to it in your documentation.

**Comment by yigitm** [comment]
Below suggestions are done. Thank you.

- You can delete the Main.js as it is part of your previous milestone.
- You can include a screenshot of your project in the Readme file to improve your documentation.
- It would be very good to deploy your application and include a link to it in your documentation.
